name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: ✨ Features
    labels:
      - feat
  - title: 🐛 Bug Fixes
    labels:
      - fix
  - title: 🛠️ Chores
    labels:
      - chore
  - title: 🏗️ Build System
    labels:
      - build
  - title: ⚡ Performance Improvements
    labels:
      - perf
  - title: 🔨 Refactors
    labels:
      - refactor
  - title: 🎨 Code Style Updates
    labels:
      - style

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
template: |
  ## 🔥 What's Changed

  $CHANGES

  ---
  🔖 Compare Changes: [View Changes](https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION)