name: mood_diary
description: "A new Flutter project."
publish_to: 'none'
version: 2.6.0+60

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: 5.0.0-release-candidate-9.2.1
  dio: 5.7.0
  path: 1.9.0
  path_provider: 2.1.5
  calendar_date_picker2: 1.1.7
  logger: 2.5.0
  flutter_drawing_board: 0.9.5
  flutter_displaymode: 0.6.0
  fl_chart: 0.69.2
  file_picker: 8.1.4
  local_auth: 2.3.0
  local_auth_android: 1.0.46
  permission_handler: 11.3.1
  image_picker: 1.1.2
  device_info_plus: 11.1.1
  photo_view: 0.15.0
  package_info_plus: 8.1.1
  uuid: 4.5.1
  flutter_quill: 11.0.0-dev.14
  share_plus: 10.1.2
  url_launcher: 6.3.1
  archive: 3.6.1
  crypto: 3.0.6
  markdown_widget: 2.3.2+6
  flutter_colorpicker: 1.1.0
  geolocator: 13.0.2
  shared_preferences: 2.3.3
  isar: 4.0.0-dev.14
  isar_flutter_libs: 4.0.0-dev.14
  fluttertoast: 8.2.8
  cached_network_image: 3.4.1
  audioplayers: 6.1.0
  record: 5.2.0
  duration: 4.0.3
  dynamic_color: 1.7.0
  supabase_flutter: 2.8.1
  bitsdojo_window: 0.1.6
  intl: 0.19.0
  collection: 1.19.0
  cupertino_icons: 1.0.8
  font_awesome_flutter: 10.8.0
  tflite_flutter: 0.11.0
  sliver_tools: 0.2.12
  lottie: 3.2.0
  media_kit: 1.1.11
  media_kit_video: 1.2.5
  media_kit_libs_video: 1.0.5
  flutter_adaptive_scaffold: 0.3.1
  cross_file: 0.3.4+2
  fc_native_video_thumbnail: 0.16.1
  flutter_map: 7.0.2
  flutter_map_tile_caching: 9.1.4
  flutter_map_marker_cluster: 1.4.0
  latlong2: 0.9.1
  shelf: 1.4.2
  shelf_multipart: 2.0.0
  waterfall_flow: 3.1.0
  smooth_page_indicator: 1.2.0+3
  table_calendar: 3.1.2
  unicons: 3.0.0
  network_info_plus: 6.1.1
  encrypt: 5.0.3
  objectbox: 4.0.3
  faker: 2.2.0
  flutter_inappwebview: 6.1.5
  flutter_rust_bridge: 2.6.0
  syncfusion_flutter_sliders: 27.2.5
  flutter_quill_extensions: 11.0.0-dev.4
  connectivity_plus: 6.1.0
  image_picker_android: 0.8.12+18
  video_player_media_kit: 1.0.5
  video_player: 2.9.2
  chewie: 1.8.5
  http_status_code: 0.0.2
  pinput: 5.0.0
  flutter_markdown: 0.7.4+3
  google_fonts: 6.2.1
  image_picker_platform_interface: 2.10.0
  chinese_font_library: 1.2.0
  flutter_image_compress: 2.3.0
  mime: 1.0.6
  auto_size_text_field: 2.2.4
  webdav_client: 1.2.2
  confetti: 0.8.0
  flutter_native_splash: 2.4.3
  flutter_localizations:
    sdk: flutter
  rust_lib_mood_diary:
    path: rust_builder

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.13
  flutter_launcher_icons: 0.14.2
  msix: 3.16.8
  flutter_lints: 5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/light/light_foreground.png"
  adaptive_icon_monochrome: "assets/icon/light/light_foreground.png"
  image_path_ios_dark_transparent: "assets/icon/dark/dark_foreground.png"
  image_path_ios_tinted_grayscale: "assets/icon/light/light_foreground.png"
  desaturate_tinted_to_grayscale_ios: true
  image_path: "assets/icon/light/light_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 26
  windows:
    generate: true
    image_path: "assets/icon/light/light_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/light/light_icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/light/light_splash_icon.png
  color_dark: "#000000"
  image_dark: assets/icon/dark/dark_splash_icon.png

  android_12:
    image: assets/icon/light/light_splash_icon.png
    color: "#ffffff"
    image_dark: assets/icon/dark/dark_splash_icon.png
    color_dark: "#000000"

  web: false

  # Platform specific images can be specified with the following parameters, which will override
  # the respective parameter.  You may specify all, selected, or none of these parameters:
  #color_android: "#42a5f5"
  #color_dark_android: "#042a49"
  #color_ios: "#42a5f5"
  #color_dark_ios: "#042a49"
  #color_web: "#42a5f5"
  #color_dark_web: "#042a49"
  #image_android: assets/splash-android.png
  #image_dark_android: assets/splash-invert-android.png
  #image_ios: assets/splash-ios.png
  #image_dark_ios: assets/splash-invert-ios.png
  #image_web: assets/splash-web.gif
  #image_dark_web: assets/splash-invert-web.gif
  #background_image_android: "assets/background-android.png"
  #background_image_dark_android: "assets/dark-background-android.png"
  #background_image_ios: "assets/background-ios.png"
  #background_image_dark_ios: "assets/dark-background-ios.png"
  #background_image_web: "assets/background-web.png"
  #background_image_dark_web: "assets/dark-background-web.png"
  #branding_android: assets/brand-android.png
  #branding_bottom_padding_android: 24
  #branding_dark_android: assets/dart_dark-android.png
  #branding_ios: assets/brand-ios.png
  #branding_bottom_padding_ios: 24
  #branding_dark_ios: assets/dart_dark-ios.png
  #branding_web: assets/brand-web.gif
  #branding_dark_web: assets/dart_dark-web.gif

  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center

  # The screen orientation can be set in Android with the android_screen_orientation parameter.
  # Valid parameters can be found here:
  # https://developer.android.com/guide/topics/manifest/activity-element#screen
  #android_screen_orientation: sensorLandscape

  # To hide the notification bar, use the fullscreen parameter.  Has no effect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual, overlays: [SystemUiOverlay.bottom, SystemUiOverlay.top], );
  #fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'

flutter:
  generate: true
  fonts:
    - family: qweather
      fonts:
        - asset: assets/fonts/qweather-icons.ttf

  assets:
    - assets/icon/dark/
    - assets/icon/light/
    - assets/lottie/

  uses-material-design: true


